version: '3'
services:
  rmi-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: rmi-server
    networks:
      - rmi-network
    expose:
      - "1099"
      - "1300"

  rmi-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: rmi-client
    networks:
      - rmi-network
    depends_on:
      - rmi-server  # Make sure server starts before client
    stdin_open: true # Keep stdin open for interactivity
    tty: true
networks:
  rmi-network:
    driver: bridge