version: '3'
services:

  coordinator:
    build:
      context: .
      dockerfile: Dockerfile.coordinator
    container_name: coordinator
    networks:
      - rmi-network
    depends_on:
      - rmi-server-1  # Make sure servers start before coordinator
      - rmi-server-2
      - rmi-server-3
      - rmi-server-4
      - rmi-server-5
    ports:
      - "2099:2099"
    environment:
      SERVER_NAME: "coordinator"

  rmi-server-1:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: rmi-server-1
    networks:
      - rmi-network
    ports:
      - "8081:1099" # RMI port maps to 8081 on host
      - "1301:1300"
    environment:
      SERVER_NAME: "rmi-server-1"

  rmi-server-2:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: rmi-server-2
    networks:
      - rmi-network
    ports:
      - "8082:1099" # RMI port maps to 8082 on host
      - "1302:1300"
    environment:
      SERVER_NAME: "rmi-server-2"

  rmi-server-3:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: rmi-server-3
    networks:
      - rmi-network
    ports:
      - "8083:1099" # RMI port maps to 8083 on host
      - "1303:1300"
    environment:
      SERVER_NAME: "rmi-server-3"

  rmi-server-4:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: rmi-server-4
    networks:
      - rmi-network
    ports:
      - "8084:1099" # RMI port maps to 8084 on host
      - "1304:1300"
    environment:
      SERVER_NAME: "rmi-server-4"

  rmi-server-5:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: rmi-server-5
    networks:
      - rmi-network
    ports:
      - "8085:1099" # RMI port maps to 8085 on host
      - "1305:1300"
    environment:
      SERVER_NAME: "rmi-server-5"

  rmi-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: rmi-client
    networks:
      - rmi-network
    depends_on:
      - rmi-server-1  # Make sure servers start before client
      - rmi-server-2
      - rmi-server-3
      - rmi-server-4
      - rmi-server-5
    stdin_open: true # Keep stdin open for interactivity
    tty: true
networks:
  rmi-network:
    driver: bridge