# Dockerfile for client

# Set base image to OpenJDK 19
FROM openjdk:19-jdk

# Set working directory inside the container
WORKDIR /app

COPY Client.java /app
COPY RemoteOperations.java /app

# Expose ports for server and rmiregistry
EXPOSE 1099 1300

# Compile Server and RemoteOperations files
RUN javac Client.java RemoteOperations.java

CMD [ "java", "Client", "127.0.0.2", "1300"]
